# Fluxo de trabalho para construir e implantar um site Hugo no GitHub Pages
name: Implantar site Hugo no GitHub Pages

on:
  # Executa nas alterações do ramo padrão
  push:
    branches: ["main"]

  # Permite que você execute este fluxo de trabalho manualmente a partir da guia Actions
  workflow_dispatch:

# Define permissões do GITHUB_TOKEN para permitir a implantação no GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Permite apenas uma implantação simultânea, pulando execuções enfileiradas entre a execução em andamento e a mais recente enfileirada.
# No entanto, NÃO cancela execuções em andamento, pois queremos permitir que essas implantações de produção sejam concluídas.
concurrency:
  group: "pages"
  cancel-in-progress: false

# Define o shell como bash por padrão
defaults:
  run:
    shell: bash

jobs:
  # Job de construção
  build:
    runs-on: ubuntu-latest
    env:
      HUGO_VERSION: 0.128.0
    steps:
      - name: Instalar Hugo CLI
        run: |
          wget -O ${{ runner.temp }}/hugo.deb https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_linux-amd64.deb \
          && sudo dpkg -i ${{ runner.temp }}/hugo.deb
      - name: Instalar

